
### 보드 생성
POST http://localhost:8080/api/boards
Authorization:{{Authorization}}
Content-Type: application/json

{
  "boardName": "board",
  "content": "내용 테스트"
}

### 보드 조회
GET http://localhost:8080/api/boards/2?page=0&size=5
Authorization:{{Authorization}}
Content-Type: application/json

### 보드 수정
PUT http://localhost:8080/api/boards/2
Authorization:{{Authorization}}
Content-Type: application/json

{
  "boardName" : "보드 수정테스트",
  "content" : "내용 수정테스트"
}

### 보드 삭제
DELETE http://localhost:8080/api/boards/8
Authorization:{{Authorization}}
Content-Type: application/json


### 보드 사용자 초대
POST http://localhost:8080/api/boards/members
Authorization:{{Authorization}}
Content-Type: application/json

{
  "boardId": 1,
  "memberIdList": [1]
}